# Generated by Django 5.1.4 on 2026-07-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('mention', 'Mention'), ('task_assigned', 'Task assigned'), ('task_updated', 'Task updated'), ('comment_reply', 'Comment reply'), ('workspace_invite', 'Workspace invite'), ('handover_submitted', 'Handover submitted'), ('handover_reviewed', 'Handover reviewed'), ('system', 'System')], max_length=32),
        ),
    ]
